# Nexus Configuration
nexusHost=192.168.1.100
nexusPort=8091
nexusNpmRepo=npm-hosted
nexusMavenRepo=maven-releases
#nexusUsername=admin
#nexusPassword=changeme

# UI Configuration
uiPackageName=ffxi-stats
uiPackageVersion=1.0.0