const playerSchema = {
  abilities: Array,
  attack: Number,
  buffs: {
    type: Map,
    of: {
      buff_id: Number,
      buff_name: String,
      buff_duration: Number,
      utc_time: String,
    }
  },
  currency1: {
    conquestPointsBastok: Number,
    conquestPointsSandoria: Number,
    conquestPointsWindurst: Number,
    deeds: Number,
    dominionNotes: Number,
    imperialStanding: Number,
    loginPoints: Number,
    nyzulTokens: Number,
    sparksOfEminence: Number,
    therionIchor: Number,
    unityAccolades: Number,
    voidstones: Number,
  },
  currency2: {
    coalitionImprimaturs: Number,
    domainPoints: Number,
    eschaBeads: Number,
    eschaSilt: Number,
    gallantry: Number,
    gallimaufry: Number,
    hallmarks: Number,
    mogSegments: Number,
    mweyaPlasmCorpuscles: Number,
    potpourri: Number,
  },
  currentExemplar: Number,
  defense: Number,
  expHistory: {
    experience: {
      type: Array,
      default: [],
      of: {
        points: Number,
        chain: Number,
        timestamp: String,
      }
    },
    capacity: {
      type: Array,
      default: [],
      of: {
        points: Number,
        chain: Number,
        timestamp: String,
      }
    },
    exemplar: {
      type: Array,
      default: [],
      of: {
        points: Number,
        chain: Number,
        timestamp: String,
      }
    },
  },
  gil: Number,
  hpp: Number,
  lastOnline: Number,
  mainJob: String,
  mainJobLevel: Number,
  masterLevel: Number,
  merits: {
    total: Number,
    max: Number,
  },
  capacityPoints: {
    total: Number,
  },
  mpp: Number,
  nationRank: Number,
  playerId: Number,
  playerName: String,
  requiredExemplar: Number,
  stats: {
    baseSTR: Number,
    baseDEX: Number,
    baseVIT: Number,
    baseAGI: Number,
    baseINT: Number,
    baseMND: Number,
    baseCHR: Number,
    addedSTR: Number,
    addedDEX: Number,
    addedVIT: Number,
    addedAGI: Number,
    addedINT: Number,
    addedMND: Number,
    addedCHR: Number,
    fireResistance: Number,
    iceResistance: Number,
    windResistance: Number,
    earthResistance: Number,
    lightningResistance: Number,
    waterResistance: Number,
    lightResistance: Number,
    darkResistance: Number,
  },
  status: Number,
  subJob: String,
  subJobLevel: Number,
  title: String,
  tp: Number,
  zone: String,
}

module.exports = playerSchema;