const userSchema = {
  abilities: Array,
  attack: Number,
  buffs: String,
  currency1: {
    conquestPointsBastok: Number,
    conquestPointsSandoria: Number,
    conquestPointsWindurst: Number,
    deeds: Number,
    dominionNotes: Number,
    imperialStanding: Number,
    loginPoints: Number,
    nyzulTokens: Number,
    sparksOfEminence: Number,
    therionIchor: Number,
    unityAccolades: Number,
    voidstones: Number,
  },
  currency2: {
    coalitionImprimaturs: Number,
    domainPoints: Number,
    eschaBeads: Number,
    eschaSilt: Number,
    gallantry: Number,
    gallimaufry: Number,
    hallmarks: Number,
    mogSegments: Number,
    mweyaPlasmCorpuscles: Number,
    potpourri: Number,
  },
  currentExemplar: Number,
  defense: Number,
  gil: Number,
  hpp: Number,
  lastOnline: Number,
  mainJob: String,
  mainJobLevel: Number,
  masterLevel: Number,
  mpp: Number,
  nationRank: Number,
  playerId: Number,
  playerName: String,
  requiredExemplar: Number,
  stats: {
    baseSTR: Number,
    baseDEX: Number,
    baseVIT: Number,
    baseAGI: Number,
    baseINT: Number,
    baseMND: Number,
    baseCHR: Number,
    addedSTR: Number,
    addedDEX: Number,
    addedVIT: Number,
    addedAGI: Number,
    addedINT: Number,
    addedMND: Number,
    addedCHR: Number,
    fireResistance: Number,
    iceResistance: Number,
    windResistance: Number,
    earthResistance: Number,
    lightningResistance: Number,
    waterResistance: Number,
    lightResistance: Number,
    darkResistance: Number,
  },
  status: Number,
  subJob: String,
  subJobLevel: Number,
  title: String,
  tp: Number,
  zone: String,
}

module.exports = userSchema;