const userSchema = {
  abilities: Array,
  attack: Number,
  buffs: String,
  currentExemplar: Number,
  defense: Number,
  lastOnline: Number,
  mainJobLevel: Number,
  masterLevel: Number,
  nationRank: Number,
  requiredExemplar: Number,
  status: Number,
  currency2: {
    domainPoints: Number,
    eschaBeads: Number,
    eschaSilt: Number,
    gallantry: Number,
    gallimaufry: Number,
    hallmarks: Number,
    mogSegments: Number,
    mweyaPlasmCorpuscles: Number,
    potpourri: Number,
  },
  stats: {
    baseSTR: Number,
    baseDEX: Number,
    baseVIT: Number,
    baseAGI: Number,
    baseINT: Number,
    baseMND: Number,
    baseCHR: Number,
    addedSTR: Number,
    addedDEX: Number,
    addedVIT: Number,
    addedAGI: Number,
    addedINT: Number,
    addedMND: Number,
    addedCHR: Number,
    fireResistance: Number,
    iceResistance: Number,
    windResistance: Number,
    earthResistance: Number,
    lightningResistance: Number,
    waterResistance: Number,
    lightResistance: Number,
    darkResistance: Number,
  },
  hpp: Number,
  mainJob: String,
  mpp: Number,
  playerName: String,
  subJob: String,
  subJobLevel: Number,
  title: String,
  tp: Number,
  zone: String,
}

module.exports = userSchema;